---
- name: Testing firewall
  hosts: all
  tasks:
  - name: Denying port 80
    win_firewall_rule:
      name: testing
      state: absent
      enable: true
      localport: 80
      action: block
      direction: In
      protocol: TCP
  - name: Verify if an HTTP website (port 80) is accessible
    uri:
      url: http://ec2-18-141-57-13.ap-southeast-1.compute.amazonaws.com
      return_content: yes
      status_code: 200
    delegate_to: localhost
    register: out
  - name: Printing the output
    debug:
      var: out